### ISSUE TITLE
Cannot assign requested address

### ISSUE THREAD

**Issue by ghost** [mcuadros/gce-docker#1]
Following the installation steps I got this error while trying to create the disk : 

`create my-disk: Error looking up volume plugin gce: Post http://[::]:5678/Plugin.Activate: dial tcp [::]:5678: connect: cannot assign requested address`

**Comment by mcuadros** [comment]
In witch Host OS are you running? Is tested under CoreOS, but I found a similar error running it on Debian

**Comment by mcuadros** [comment]
@naptiv I just uploaded a new version, so make: (the run command is a new one) 

```
docker run -d -v /:/rootfs -v /run/docker/plugins:/run/docker/plugins -v /var/run/docker.sock:/var/run/docker.sock --privileged mcuadros/gce-docker
```
