### ISSUE TITLE
Error when trying to create volume.

### ISSUE THREAD

**Issue by slooker** [mcuadros/gce-docker#5]
I follow these steps and end up with the error of it not finding the driver:

`docker volume create --driver=gce --name rethink-storage -o SizeGb=10
Error response from daemon: create rethink-storage: create rethink-storage: Error looking up volume plugin gce: legacy plugin: plugin not found`

Version: `Docker version 1.12.1, build 6f9534c`

`$ docker images
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
mcuadros/gce-docker   latest              04344d74665a        11 weeks ago        148.2 MB`

**Comment by mcuadros** [comment]
The gce-container is running? as privileged? Can you post the log of it?

**Comment by slooker** [comment]
`t=2016-09-27T13:44:26+0000 lvl=info msg="starting volume driver" project=rare-disk-144021 zone=us-central1-f instance=swarm-manager
t=2016-09-27T13:44:26+0000 lvl=info msg="starting watcher" project=rare-disk-144021 zone=us-central1-f instance=swarm-manager
t=2016-09-27T13:44:26+0000 lvl=crit msg="error creating watcher: error retrieving region from zone: googleapi: Error 403: Insufficient Permission, insufficientPermissions"
t=2016-09-27T13:44:26+0000 lvl=crit msg="error creating volume plugin: error retrieving region from zone: googleapi: Error 403: Insufficient Permission, insufficientPermissions"`

Pretty clear what the error is.  I'm just not sure how to fix it.

**Comment by mcuadros** [comment]
> The instance requires Read/Write privileges to Google Compute Engine and IP forwarding flags should be active to.

**Comment by slooker** [comment]
IP forwarding flags should be active where? 

I assumed since I had read/write access on the host, it was all I needed.  Where else do I need to enable read/write privileges?

Do you mean on the service account?  I can't find permissions on an instance.  Sorry to be dense. :/

**Comment by mcuadros** [comment]
In the instance:

`Identity and API access > Access scopes > Compute`
(you can also configure this on the service Account)

and 

`Networking > IP forwarding > On`
